In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer
def generate_example_dataset():
    data = {
        'PassengerId': [1, 2, 3, 4, 5],
        'Name': ['John', 'Jane', 'Bob', 'Alice', 'Charlie'],
        'Age': [22, None, 25, None, 30],
        'Fare': [7.25, 71.28, None, 8.05, 10.5],
        'Survived': [0, 1, 1, 0, 1]
    }
    return pd.DataFrame(data)
def clean_dataset(df):
    print("Original Dataset:")
    print(df)
    numeric_df = df.select_dtypes(include='number')
    imputer = SimpleImputer(strategy='mean')
    df_cleaned = pd.DataFrame(imputer.fit_transform(numeric_df), columns=numeric_df.columns)
    print("\nCleaned Dataset:")
    print(df_cleaned)
if __name__ == "__main__":
    example_dataset = generate_example_dataset()
    clean_dataset(example_dataset)


Original Dataset:
   PassengerId     Name   Age   Fare  Survived
0            1     John  22.0   7.25         0
1            2     Jane   NaN  71.28         1
2            3      Bob  25.0    NaN         1
3            4    Alice   NaN   8.05         0
4            5  Charlie  30.0  10.50         1

Cleaned Dataset:
   PassengerId        Age   Fare  Survived
0          1.0  22.000000   7.25       0.0
1          2.0  25.666667  71.28       1.0
2          3.0  25.000000  24.27       1.0
3          4.0  25.666667   8.05       0.0
4          5.0  30.000000  10.50       1.0


In [7]:
import numpy as np

In [9]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [10]:
b[2] # 2nd row0

array([71, 56, 51, 58, 59, 47, 68, 77])

In [11]:
b[:,7] #7th column

array([53, 60, 77, 55, 51, 47, 61])

In [12]:
b[:,3] 

array([67, 77, 58, 74, 69, 77, 69])

In [13]:
b[1,3]

77

In [14]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [15]:
b[2,1:6]

array([56, 51, 58, 59, 47])

In [18]:
array[ row_start : row-end : row-step]

NameError: name 'array' is not defined

In [20]:
b[1:6:2,1:6]

array([[59, 55, 77, 69, 69],
       [45, 52, 74, 65, 53],
       [67, 53, 77, 60, 67]])

In [21]:
b[3:6,2:6]

array([[52, 74, 65, 53],
       [46, 69, 65, 75],
       [53, 77, 60, 67]])

In [22]:
b[1:6:2]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [24]:
b[1:6:2,1:8:3]

array([[59, 69, 60],
       [45, 65, 55],
       [67, 60, 47]])